### ISSUE TITLE
Take applicant off of application now that IDV has completed

### ISSUE THREAD

**Issue by melgeyer** [seedco/highpri#1]
### Business impacted
Coffeeinne, Inc

### Last 4 digits of Acct Number
None. Applicant 

### Customer name who reported issue
None.

### Issue described
Un-associate Francisco Alexander Noguera Bermudez from the Coffeeinne application so that we can approve the account.

**Comment by tn-** [comment]
I've manually updated `Francisco Alexander Noguera Bermudez`'s status to Rejected in the app, and removed him from `Coffeeine`. The app should now be good to submit; let me know if you run into any issues!

**Comment by melgeyer** [comment]
Thanks, @tn- 

@lh12345 has zen ticket (https://seedinc.zendesk.com/agent/tickets/795) and will likely open account today.

**Comment by lh12345** [comment]
acct opened - thanks @melgeyer and @tn- for addressing this unique case.
