### ISSUE TITLE
Card Replace (not reissue)

### ISSUE THREAD

**Issue by melgeyer** [seedco/highpri#3]
### Business impacted
Viktor Radchenko 

### Last 4 digits of Acct Number
(x696)

### Customer name who reported issue
Viktor 

### Issue described
Lost wallet, needs new card. This would be a replacement (new numbers) since the card is missing and not just damaged.

**Comment by tn-** [comment]
The card has been replaced

**Comment by melgeyer** [comment]
Thanks, @tn- !
