### ISSUE TITLE
Application Issue

### ISSUE THREAD

**Issue by rachaelwoolen** [seedco/highpri#5]
### Business impacted
Abraven Studios

### Last 4 digits of Acct Number
n/a

### Customer name who reported issue
Daniel Stephen Clark

### Issue described
Customer accidentally selected multiple owners and sent himself another invite. Do we need to or can we do anything to fix this?

cc @adelelopez

**Comment by adelelopez** [comment]
I can delete the extra owner manually.

**Comment by rachaelwoolen** [comment]
Awesome, do I need to tell the customer to do anything else?

**Comment by adelelopez** [comment]
I've deleted the extra invite. Everything should be fine now. No further action should be needed.
