### ISSUE TITLE
Balance is wrong

### ISSUE THREAD

**Issue by melgeyer** [seedco/highpri#6]
### Business impacted
Snap Creative

### Last 4 digits of Acct Number
x638

### Customer name who reported issue
Myron Cridge

### Issue described
1. His balance seems wrong. If you do the math, it's off.

2. His check, deposited yesterday shows as posted in the transaction list, but should not be cleared b/c of normal check hold (see his screenshot). If it should be cleared/posted then it should also be reflected in the balance, but it's not. 

### Related notes, steps to reproduce, etc.

![image](https://cloud.githubusercontent.com/assets/25039577/26127283/abbe5ecc-3a3d-11e7-9f48-4c133b5a20cd.png)

**Comment by benjisg** [comment]
@john-cai looks like the transaction for this one is showing as settled but maybe Bancorp isn't recognizing it in the balance? What's the best way to confirm?

Transaction id: `071468f7-830d-415f-a51e-3f0754f21897`

```
{"rdc": true, "check": true, "saved": true, "bancorp": true, "deposit": true, "settled": true}
``

**Comment by john-cai** [comment]
what's happening here is that $200 of the $845  is available, the rest is held by bancorp. the 99.99 is a hold. 200-99.99 = 100.01

**Comment by melgeyer** [comment]
thanks for clearing this up, @john-cai. I let the customer know what's happening and consider this issue resolved from the support pov. support issue: https://seedinc.zendesk.com/agent/tickets/873

I shared the info with @rachaelwoolen so we're both aware in case customer contact comes in. 

cc: @ryanhildebrand in case you have to cover support, you might read this over and check out my response to the customer in the above zen issue link to understand this issue. It'll be around for a bit while we figure out how to display it correctly.
